# POST http://localhost:5000/api/signUp 
# Content-Type: application/json

#   {
#       "fullname":"Janarthanan",
#       "email": "janarthanan@gmail.com",
#       "password": "Janarthanan2103"
#   }

# token- eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzhmMzE4MDA0OTM1NjAwNWJhNzU4NiIsImlhdCI6MTcxOTIwMjU4NH0.C2THrCqWob_1Np_vP0kDlMC1Ff5dLkaGdgukwR2W_o4

# POST http://localhost:5000/api/signin
# Content-Type: application/json

# {
#     "email": "janarthanan@gmail.com",
#     "password": "Janarthanan2103"
# } 

# POST http://localhost:5000/api/blog/getBlogs
# Content-Type: application/json

# {
#   "blog_id":"The-Ultimate-Guide-to-Effective-Weeding-Tips-and-Techniques-for-a-Pristine-Garden-zaj-OATJhCjid1ZPZFkSF"
# }

# POST  http://localhost:5000/api/getUserProfile
# Content-Type: application/json

# {
#   "username" : "janarthananv2107"
# }

# # GET http://localhost:5000/api/blog/trendingBlogs
# POST http://localhost:5000/api/blog/searchBlogs

# {
#   "tag":""
# }


# POST http://localhost:5000/api/upload/image

# {
#   "image":"https://example.com/dfdfd"
# }